server:
  port: 8081
  servlet:
    context-path: /mybatis
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/honor?currentSchema=pressfree
    username: postgres
    password: power.huang
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Invoked
      minimum-idle: 3
      maximum-pool-size: 12
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1200000
mybatis:
  mapper-locations: classpath:org/hjz/mybatis/common/mapper/**.xml
  type-aliases-package: org.hjz.mybatis.common.model